/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg430test;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Scott
 */
public class FacultyForm extends javax.swing.JFrame {

    /**
     * Creates new form FacultyForm
     */
    public FacultyForm() {
        initComponents();
        setTitle("Faculty");
        updateFacultyTable();
        updateStudentTable();
        updateDepartmentTable();
        updateCoursesTable();
        updateEnrolledTable();
    }
    
    private void updateFacultyTable()
    {
        try {
            try (Connection conn = ConnectionConfig.getConnection()) {
                PreparedStatement st = conn.prepareStatement("Select A.FNAME, A.DEPTID, B.DNAME from Faculty A JOIN Department B ON A.DEPTID = B.DID ORDER BY A.FNAME ASC");
                ResultSet rs = st.executeQuery();
                FacultyFacultyTable.setModel(DbUtils.resultSetToTableModel(rs));
                conn.close();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }
    private void updateStudentTable()
    {
        try {
            try (Connection conn = ConnectionConfig.getConnection()) {
                PreparedStatement st = conn.prepareStatement("Select * from Students ORDER BY SNAME ASC");
                ResultSet rs = st.executeQuery();
                FacultyStudentTable.setModel(DbUtils.resultSetToTableModel(rs));
                conn.close();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }
     private void updateEnrolledTable()
    {
        try {
            try (Connection conn = ConnectionConfig.getConnection()) {
                PreparedStatement st = conn.prepareStatement("Select A.SID, B.SNAME, A.EXAM1, A.EXAM2, A.FINAL from Enrolled A JOIN Students B ON A.SID = B.SID ORDER BY B.SNAME");
                ResultSet rs = st.executeQuery();
                FacultyEnrolledTable.setModel(DbUtils.resultSetToTableModel(rs));
                conn.close();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }
     
     private void updateDepartmentTable()
    {
        try {
            try (Connection conn = ConnectionConfig.getConnection()) {
                PreparedStatement st = conn.prepareStatement("Select * from DEPARTMENT ORDER BY DNAME ASC");
                ResultSet rs = st.executeQuery();
                FacultyDeptTable.setModel(DbUtils.resultSetToTableModel(rs));
                conn.close();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }
      private void updateCoursesTable()
    {
        try {
            try (Connection conn = ConnectionConfig.getConnection()) {
                PreparedStatement st = conn.prepareStatement("Select A.CID, A.CNAME, A.MEETS_AT, A.ROOM, A.FID, B.FNAME, A. LIMIT from COURSES A JOIN FACULTY B ON A.FID = B.FID ORDER BY CID ASC");
                ResultSet rs = st.executeQuery();
                FacultyCoursesTable.setModel(DbUtils.resultSetToTableModel(rs));
                conn.close();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        FacultyFacultyTab = new javax.swing.JTabbedPane();
        FacultyFacultyTab2 = new javax.swing.JScrollPane();
        FacultyFacultyTable = new javax.swing.JTable();
        FacultyStudentTab = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        FacultyStudentTable = new javax.swing.JTable();
        FacultyEnrolledTab = new javax.swing.JTabbedPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        FacultyEnrolledTable = new javax.swing.JTable();
        FacultyDepartmentsTab = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        FacultyDeptTable = new javax.swing.JTable();
        FacultyCoursesTab = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        FacultyCoursesTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FacultyFacultyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        FacultyFacultyTab2.setViewportView(FacultyFacultyTable);

        FacultyFacultyTab.addTab("Faculty", FacultyFacultyTab2);

        jTabbedPane1.addTab("Faculty", FacultyFacultyTab);

        FacultyStudentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(FacultyStudentTable);

        FacultyStudentTab.addTab("Students", jScrollPane1);

        jTabbedPane1.addTab("Students", FacultyStudentTab);

        FacultyEnrolledTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(FacultyEnrolledTable);

        FacultyEnrolledTab.addTab("Enrolled", jScrollPane4);

        jTabbedPane1.addTab("Enrolled", FacultyEnrolledTab);

        FacultyDeptTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(FacultyDeptTable);

        FacultyDepartmentsTab.addTab("Departments", jScrollPane2);

        jTabbedPane1.addTab("Departments", FacultyDepartmentsTab);

        FacultyCoursesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(FacultyCoursesTable);

        FacultyCoursesTab.addTab("Courses", jScrollPane3);

        jTabbedPane1.addTab("Courses", FacultyCoursesTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacultyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacultyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacultyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacultyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FacultyForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane FacultyCoursesTab;
    private javax.swing.JTable FacultyCoursesTable;
    private javax.swing.JTabbedPane FacultyDepartmentsTab;
    private javax.swing.JTable FacultyDeptTable;
    private javax.swing.JTabbedPane FacultyEnrolledTab;
    private javax.swing.JTable FacultyEnrolledTable;
    private javax.swing.JTabbedPane FacultyFacultyTab;
    private javax.swing.JScrollPane FacultyFacultyTab2;
    private javax.swing.JTable FacultyFacultyTable;
    private javax.swing.JTabbedPane FacultyStudentTab;
    private javax.swing.JTable FacultyStudentTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
